const urlJson = {
    "url_major": "http://localhost:8081/E_mall_API/",
    "url_addition": "http://localhost:8081/E_mall_API/",
    "login": "UserLogin",
    "register": "Register",
    "emailVerify": "EmailVerify",
    "orderList": "OrderHistory",
    "confirmOrder": "OrderConfirmation",
    "goodsInfo": "GoodsInfo",
    "AllGoodsInfoQuery": "AllGoodsInfoQuery",
    "SingleGoodQuery": "SingleGoodQuery",
    "AdministratorNumber": "AdministratorOperationAmount",
    "AdministratorPrice": "AdministratorModifyPrice",
    "CartQuery": "CartQuery",
    "CartModify" :"CartModify",
    "Purchase" :"Purchase",
    "FindAllUserInfo": "FindAllUserInfo",
    "ModifyUserInfo": "ModifyUserInfo",
    "ModifyUserStatus": "ModifyUserStatus",
    "UserAdmin": "UserAdmin",
    "UserIconUpload": "UserIconUpload",
    "PictureDownload": "PictureDownload",
    "CheckUserIcon": "CheckUserIcon"
}